### ISSUE TITLE
SHTns?

### ISSUE THREAD

**Issue by milankl** [fgerick/Limace.jl#12]
I see that you have written a wrapper for this C++ library. What functionality around spherical harmonic transforms do you need? Reason I am asking is that in SpeedyWeather we have the submodule SpeedyTransforms (which should be eventually standalone) that does transforms on any ring grid, has a neat user interface and is quite efficient. I have not compared with SHTns but we do all sorts of shortcuts so I wouldn't be surprised if we're actually faster (especially on the reduced grids)

**Comment by fgerick** [comment]
`SHTns.jl` provides convenient and very fast methods to compute vector spherical harmonics transforms https://nschaeff.bitbucket.io/shtns/vsh.html that are used for the spectral transforms of the 3D vector fields (velocity and magnetic field) in `Limace.jl`. I am not sure that SpeedyTransforms provides similar functionality? SHTns is heavily optimized also (https://nschaeff.bitbucket.io/shtns/bench.html), but I'd be happy to see a comparison.

**Comment by milankl** [comment]
Okay that's cool I hadn't seen the benchmarks there. Thanks for sharing!

![image](https://github.com/user-attachments/assets/2d5c1951-0113-4c89-8d1c-19fd7e1ad6a4)

looks like (on my intel macbook air from 2020) we're always within 2x of SHTns and therefore faster than all the other libraries (yay 🥳 ), I reckon on the newer arm chips with SVE2 we're faster, but need to check that. Whatever also is a fair comparison to the reported Intel Xeon's I don't know. I assume those benchmarks are with linear truncation so a 64x64 lower triangular matrix for $l_{max} = 63$ maps to a 128x64 full Gaussian grid? Also this is spherical harmonics to grid, and we use a general offset rotation for compatibility with HEALPix grids too.

| $l_{max}$ | SpeedyTransforms | SHTns | 
| - | - | - |
| 63 | 0.095 ms | 0.09 ms |
| 127 | 0.76 ms | 0.6 ms |
| 255 | 6.4 ms | 4.2 ms |
| 511 | 47.8 ms | 28 ms |
| 1023 | 356 ms | 216 ms |
| 2047 | 3.1 s | 1.6 s |
| 4095 | (out of memory*) | 11.8s |

* we removed the Legendre recalculation recently, but for these resolutions we could put that back in.

benchmarked with

```julia
lmax = 63
L = randn(LowerTriangularMatrix{ComplexF32}, lmax+1, lmax+1)
grid = zeros(FullGaussianGrid{Float32}, (lmax+1)÷2)
S = SpectralTransform(L, grid)

# SpectralTransform{Float32, Array}:
# ├ Spectral:   T63, 64x64 LowerTriangularMatrix{Complex{Float32}}
# ├ Grid:       64-ring FullGaussianArray{Float32}
# ├ Truncation: dealiasing = 1 (linear)
# ├ Legendre:   Polynomials 266.31 KB, shortcut: linear
# └ Memory:     for 1 layers (34.50 KB)

@btime transform!($grid, $L, $S);
#  95.734 μs (128 allocations: 7.00 KiB)
```

**Comment by milankl** [comment]
(leaving this issue open for now, but don't see it as a TODO for JOSS)

**Comment by milankl** [comment]
> Have you tested SpeedyTransforms for these high degrees?

No, although I don't know whether that's our fault or whether it's about differences in how SHTns and AssociatedLegendrePolynomials calculates the polynomials? Cause otherwise I wouldn't know where this comes from. I know that eventually the algorithm used isn't precise anymore because afaik doesn't do the rescaling that SHTns does.

> I do not think using SpeedyTransforms in this package here gives any advantage

No no, I wasn't expecting that, more out of curiosity of what are requirements for you on a transform library. Happy for you to close

**Comment by fgerick** [comment]
I'm not sure what the problem is, it seems like rescaling to avoid rounding errors at large degrees may be a reason!

I just found also (I believe it was made public not long ago) another wrapper around SHTns: https://github.com/ClimFlows/SHTnsSpheres.jl . They give custom Zygote.jl adjoints for the spherical harmonic transforms. This may be of interest to you and your project. I believe having GPU-enabled SHTns with custom adjoints would result in significant speedups.

**Comment by milankl** [comment]
Thanks for sharing! While SHTns has many of the functionality you need it doesn't have the functionality we need: grid-flexible transforms. I think it says they do Gaussian and Clenshaw-Curtis quadrature but only for full grids not reduced grids. Our default is the octahedral Gaussian grid, but we also have HEALPix, and two new custom grids OctaHEALPix and OctaminimalGaussian. See here https://speedyweather.github.io/SpeedyWeather.jl/dev/grids/
